main: org.nyanneko0113.player_manager.PlayerManager
version: 0.0.1_beta
name: PlayerManager

commands:
  normal_mute:
    description: ミュートするコマンド
    permission: playermanager.commands.normalmute
  temp_mute:
    description: ミュートするコマンド
    permission: playermanager.commands.tempmute
  mute_list:
    description: ミュートのリストを表示するコマンド
    permission: playermanager.commands.mute_list
  unmute:
    description: ミュートを解除するコマンド
    permission: playermanager.commands.unmute
  normal_ban:
    description: Banするコマンド
    permission: playermanager.commands.normalmute
  temp_ban:
    description: tempBanするコマンド
    permission: playermanager.commands.tempban
  unban:
    description: Banを解除するコマンド
    permission: playermanager.commands.unban
  ban_list:
    description: Banするコマンド
    permission: playermanager.commands.normalmute
  playerinfo:
    description: プレイヤーの情報を取得するコマンド
    permission: playermanager.commands.playerinfo
  open_inv:
    description: プレイヤーのインベントリを取得するコマンド
    permission: playermanager.commands.open_inv
  kick:
    description: プレイヤーをキックするコマンド
    permission: playermanager.commands.kick
  all_kick:
    description: OP以外をキックするコマンド
    permission: playermanager.commands.allkick
  command_log:
    description: コマンドログを有効にするコマンド
    permission: playermanager.commands.command_log