main: org.nyanneko0113.player_manager.PlayerManager
version: 0.0.1_beta
name: PlayerManager

commands:
  normal_mute:
    description: ミュートするコマンド
    permission: playermanager.commands.normalmute
  temp_mute:
    description: ミュートするコマンド
    permission: playermanager.commands.temp/mute
  mute_list:
    description: ミュートのリストを表示するコマンド
    permission: playermanager.commands.mute_list
  unmute:
    description: ミュートを解除するコマンド
    permission: playermanager.commands.unmute
  playerinfo:
    description: プレイヤーの情報を取得するコマンド
    permission: playermanager.commands.playerinfo
  command_log:
    description: コマンドログを有効にするコマンド
    permission: playermanager.commands.command_log